language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: 
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

# Monitor only these branches
branches:
  only:
  - master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache